// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: camiones_logistica.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camiones_logistica_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_camiones_logistica_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_camiones_logistica_proto_rawDescGZIP(), []int{0}
}

type Informacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete int32  `protobuf:"varint,1,opt,name=id_paquete,json=idPaquete,proto3" json:"id_paquete,omitempty"`
	Estado    string `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	Intentos  int32  `protobuf:"varint,3,opt,name=intentos,proto3" json:"intentos,omitempty"`
}

func (x *Informacion) Reset() {
	*x = Informacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camiones_logistica_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Informacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Informacion) ProtoMessage() {}

func (x *Informacion) ProtoReflect() protoreflect.Message {
	mi := &file_camiones_logistica_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Informacion.ProtoReflect.Descriptor instead.
func (*Informacion) Descriptor() ([]byte, []int) {
	return file_camiones_logistica_proto_rawDescGZIP(), []int{1}
}

func (x *Informacion) GetIdPaquete() int32 {
	if x != nil {
		return x.IdPaquete
	}
	return 0
}

func (x *Informacion) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Informacion) GetIntentos() int32 {
	if x != nil {
		return x.Intentos
	}
	return 0
}

type Tipo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tipo string `protobuf:"bytes,1,opt,name=tipo,proto3" json:"tipo,omitempty"`
}

func (x *Tipo) Reset() {
	*x = Tipo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camiones_logistica_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tipo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tipo) ProtoMessage() {}

func (x *Tipo) ProtoReflect() protoreflect.Message {
	mi := &file_camiones_logistica_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tipo.ProtoReflect.Descriptor instead.
func (*Tipo) Descriptor() ([]byte, []int) {
	return file_camiones_logistica_proto_rawDescGZIP(), []int{2}
}

func (x *Tipo) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

type Paquete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdPaquete int32  `protobuf:"varint,1,opt,name=id_paquete,json=idPaquete,proto3" json:"id_paquete,omitempty"`
	Tipo      string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Valor     string `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen    string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino   string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Paquete) Reset() {
	*x = Paquete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_camiones_logistica_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Paquete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paquete) ProtoMessage() {}

func (x *Paquete) ProtoReflect() protoreflect.Message {
	mi := &file_camiones_logistica_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paquete.ProtoReflect.Descriptor instead.
func (*Paquete) Descriptor() ([]byte, []int) {
	return file_camiones_logistica_proto_rawDescGZIP(), []int{3}
}

func (x *Paquete) GetIdPaquete() int32 {
	if x != nil {
		return x.IdPaquete
	}
	return 0
}

func (x *Paquete) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Paquete) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

func (x *Paquete) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Paquete) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

var File_camiones_logistica_proto protoreflect.FileDescriptor

var file_camiones_logistica_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x60, 0x0a, 0x0b, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x71,
	0x75, 0x65, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61,
	0x71, 0x75, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x69, 0x70,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x70, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x64, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x32, 0x6d, 0x0a, 0x0f,
	0x43, 0x61, 0x6d, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2d, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x62, 0x69, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x6f,
	0x6e, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2b,
	0x0a, 0x10, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x50, 0x61, 0x71, 0x75, 0x65,
	0x74, 0x65, 0x12, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x70, 0x6f, 0x1a, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x71, 0x75, 0x65, 0x74, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_camiones_logistica_proto_rawDescOnce sync.Once
	file_camiones_logistica_proto_rawDescData = file_camiones_logistica_proto_rawDesc
)

func file_camiones_logistica_proto_rawDescGZIP() []byte {
	file_camiones_logistica_proto_rawDescOnce.Do(func() {
		file_camiones_logistica_proto_rawDescData = protoimpl.X.CompressGZIP(file_camiones_logistica_proto_rawDescData)
	})
	return file_camiones_logistica_proto_rawDescData
}

var file_camiones_logistica_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_camiones_logistica_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: pb.Empty
	(*Informacion)(nil), // 1: pb.Informacion
	(*Tipo)(nil),        // 2: pb.Tipo
	(*Paquete)(nil),     // 3: pb.Paquete
}
var file_camiones_logistica_proto_depIdxs = []int32{
	1, // 0: pb.CamionesService.CambiarEstado:input_type -> pb.Informacion
	2, // 1: pb.CamionesService.SolicitarPaquete:input_type -> pb.Tipo
	0, // 2: pb.CamionesService.CambiarEstado:output_type -> pb.Empty
	3, // 3: pb.CamionesService.SolicitarPaquete:output_type -> pb.Paquete
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_camiones_logistica_proto_init() }
func file_camiones_logistica_proto_init() {
	if File_camiones_logistica_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_camiones_logistica_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camiones_logistica_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Informacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camiones_logistica_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tipo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_camiones_logistica_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Paquete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camiones_logistica_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_camiones_logistica_proto_goTypes,
		DependencyIndexes: file_camiones_logistica_proto_depIdxs,
		MessageInfos:      file_camiones_logistica_proto_msgTypes,
	}.Build()
	File_camiones_logistica_proto = out.File
	file_camiones_logistica_proto_rawDesc = nil
	file_camiones_logistica_proto_goTypes = nil
	file_camiones_logistica_proto_depIdxs = nil
}
